#!/usr/bin/env sh
##############################################################################
##
##  Gradle start up script for POSIX generated by Gradle.
##
##############################################################################
APP_BASE_NAME=$(basename "$0")
DIR="$(cd "$(dirname "$0")" && pwd)"
DEFAULT_JVM_OPTS=""
exec java $DEFAULT_JVM_OPTS -cp "$DIR/gradle/wrapper/gradle-wrapper.jar" org.gradle.wrapper.GradleWrapperMain "$@"
